[package]
name = "Hooker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-master = "3.1.3"
crossclip = "0.7.1"
hyper-sse = "0.1.0"
lazy_static = "1.4.0"
tiny_http = "0.12.0"
